title: Herleen Sanhotra # your name (or website title) here
logo: "images/logo.jpeg" # your logo/profile picture
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently pursuing a Master's Degree in Computer Science at UNC Charlotte and graduating in May 2021. I am excited to advance my career in Data Science and have acquired skills that have enabled me to add value to the projects I have accomplished. I love animals although I am more of a dog and cat person. Swimming is not just a hobby for me, it's meditation. I started my Data Science Journey two years ago, my first project was in Jupyter Notebooks. From there I started exploring more technologies such as Google Cloud Platform, Google Colab, MySQL to name a few.  
  <br><br>
  <a href="https://www.linkedin.com/in/herleen-sanhotra/">View My LinkedIn Profile</a> 
  <br>
  <a href="Resume/Herleen_Sanhotra_Resume.pdf">Download My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
