title: Herleen Sanhotra # your name (or website title) here
logo: "images/WhatsApp Image 2023-10-26 at 3.48.11 PM.jpeg" # your logo/profile picture
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Data Analyst at WithMe Health with 2+ years of experience analyzing and processing extensive healthcare datasets to extract actionable insights that drive research and data-informed decisions.<br>
  <br>Boosted data accuracy by 15% and process optimization by 25% through custom BI platform developments and SQL optimizations.Led the successful migration of 100+ reports to Domo, enhancing user engagement by 80%. Distinguished by academic projects that utilized predictive analysis on traffic accidents and sales forecasting.Holds a Master's in Computer Science from UNC Charlotte.Skilled in Python, SQL, Domo, Microstrategy, and cloud computing technology AWS(S3, Athena, Notebooks).<br>
  <br>
  <a href="https://www.linkedin.com/in/herleen-sanhotra/">View My LinkedIn Profile</a> 
  <br>
  <a href="Resume/HERLEENSANHOTRA_RESUME.pdf">Download My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
