title: Herleen Sanhotra # your name (or website title) here
logo: "images/logo.jpeg" # your logo/profile picture
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have recently graduated from UNC Charlotte with a Master's Degree in Computer Science and Data Science as my specialization.
  <br><br>
  I am excited to advance my career in Data Science and have acquired skills that have enabled me to add value to the projects I have accomplished.
  <br><br>
  <a href="https://www.linkedin.com/in/herleen-sanhotra/">View My LinkedIn Profile</a> 
  <br>
  <a href="Resume/HerleenSanhotra_Resume.pdf">Download My Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
